name: Output information 
on: [push, workflow_dispatch] # adding manual workflow

jobs:
  info:
    runs-on: ubuntu-latest
  steps:
    - name: Output github context
      run: |
        echo "${{ github}}
        echo "${{ env }}